# Generated by Django 5.1.7 on 2025-03-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('fixed_acidity', models.FloatField(verbose_name='fixed_acidity')),
                ('volatile_acidity', models.FloatField(verbose_name='volatile_acidity')),
                ('citric_acid', models.FloatField(verbose_name='citric_acid')),
                ('residual_sugar', models.FloatField(verbose_name='residual_sugar')),
                ('chlorides', models.FloatField(verbose_name='chlorides')),
                ('free_sulfur_dioxide', models.FloatField(verbose_name='free_sulfur_dioxide')),
                ('total_sulfur_dioxide', models.FloatField(verbose_name='total_sulfur_dioxide')),
                ('density', models.FloatField(verbose_name='density')),
                ('pH', models.FloatField(verbose_name='pH')),
                ('sulphates', models.FloatField(verbose_name='sulphates')),
                ('alcohol', models.FloatField(verbose_name='alcohol')),
                ('quality', models.IntegerField(verbose_name='quality')),
                ('bin_quality', models.IntegerField(verbose_name='bin_quality')),
                ('train_set', models.BooleanField(default=True, verbose_name='train_set')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
