# Generated by Django 5.1.7 on 2025-03-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_wines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wines',
            options={'ordering': ['name'], 'verbose_name_plural': 'Wines'},
        ),
        migrations.AlterField(
            model_name='wines',
            name='alcohol',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='alcohol'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='bin_quality',
            field=models.BooleanField(verbose_name='bin_quality'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='chlorides',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='chlorides'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='citric_acid',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='citric_acid'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='density',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='density'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='fixed_acidity',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='fixed_acidity'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='free_sulfur_dioxide',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='free_sulfur_dioxide'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='pH',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='residual_sugar',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='residual_sugar'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='sulphates',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='sulphates'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='total_sulfur_dioxide',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='total_sulfur_dioxide'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='volatile_acidity',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='volatile_acidity'),
        ),
    ]
